# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_bootstrap3_modal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalcontainer',
            name='size',
            field=models.CharField(blank=True, choices=[('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')], default='md', max_length=2, verbose_name='Modal window size'),
        ),
        migrations.AddField(
            model_name='modalcontainer',
            name='top',
            field=models.CharField(blank=True, max_length=20, verbose_name='Top'),
        ),
    ]
