# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-01 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_bootstrap3_modal', '0002_auto_20160401_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalcontainer',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_bootstrap3_modal_modalcontainer', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='modalcontent',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_bootstrap3_modal_modalcontent', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='modalfooter',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_bootstrap3_modal_modalfooter', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='modalpreview',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_bootstrap3_modal_modalpreview', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='modaltitle',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_bootstrap3_modal_modaltitle', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
